#pragma config(Motor,  port2,           leftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// "#define" is a preprocessor directive that goes through the code and replaces each occurance
// of the first statement (LEFTJOY_X) with the second statement (vexRT[Ch4])
#define LEFTJOY_X vexRT[Ch4]  //X value of the left joystick
#define LEFTJOY_Y vexRT[Ch3]  //Y value of the left joystick

#define RIGHTJOY_X vexRT[Ch1] //X value of the right joystick
#define RIGHTJOY_Y vexRT[Ch2] //Y value of the right joystick


// "const" defines a variable that cannot be changed during runtime
const int joystickDeadzone = 10;


task main()
{
	while(true)
	{
		//"abs" is a default c function which returns the absolute value of an integer
		if (abs(LEFTJOY_Y) > joystickDeadzone || abs(RIGHTJOY_Y) > joystickDeadzone)
		{
			motor[leftMotor] = LEFTJOY_Y;
			motor[rightMotor] = LEFTJOY_Y;
		}
	}
}
