#pragma config(Motor,  port2,           leftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Above code is generated by RobotC when you set up motors and sensors

//vexRT[Ch#] refers to the X or Y values of the joysticks; see "Vexnet Joystick" in notebook for more
#define LEFTJOY_Y vexRT[Ch3]  //Y value of the left joystick
#define RIGHTJOY_Y vexRT[Ch2] //Y value of the right joystick

//vexRT
#define CLAWCLOSE_BTN vexRT[Btn6U] //Left trigger 1 closes claw motor
#define CLAWOPEN_BTN vexRT[Btn5U]  //Right trigger 1 opens claw motor

/*
#define LEFTJOY_Y vexRT[Ch3]

-Scans through the code before it compiles
-Each time it finds the first specified text in the code (LEFTJOY_Y above)...
-It is replaced with the second specified text (vexRT[Ch3] above)
-Useful for making code easier to read
*/

// "const" defines a variable that cannot be changed while the code is running
const int joystickDeadzone = 10;  //Used to prevent small joystick changes from moving the robot


task main()
{
	while(true)
	{
		//"abs" is a default c function which returns the absolute value of an integer
		if (abs(LEFTJOY_Y) > joystickDeadzone || abs(RIGHTJOY_Y) > joystickDeadzone)
		{
			motor[leftMotor] = -LEFTJOY_Y;
			motor[rightMotor] = -RIGHTJOY_Y;
		}
		else
		{
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}


		if (CLAWCLOSE_BTN == true)
		{
			motor[clawMotor] = 64;
		}
		else if (CLAWOPEN_BTN == true)
		{
			motor[clawMotor] = -64;
		}
		else
		{
			motor[clawMotor] = 0;
		}
	}
}
